[package]
name = "subspace-runtime-primitives"
description = "Runtime primitives for Subspace Network"
license = "GPL-3.0-or-later"
version = "0.1.0"
authors = ["Subspace Labs <https://subspace.network>"]
edition = "2021"
homepage = "https://subspace.network"
repository = "https://github.com/subspace/subspace"
include = [
	"/src",
	"/Cargo.toml",
]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
parity-scale-codec = { version = "3.1.2", default-features = false, features = ["derive"] }
parity-util-mem = { version = "0.11.0", optional = true, default-features = false, features = ["primitive-types"] }
serde = { version = "1.0.137", optional = true, features = ["derive"] }
sp-core = { version = "6.0.0", default-features = false, git = "https://github.com/subspace/substrate", rev = "5f0aa1feb7250ac7b8c1b9928f87b2420b530e22" }
sp-runtime = { version = "6.0.0", default-features = false, git = "https://github.com/subspace/substrate", rev = "5f0aa1feb7250ac7b8c1b9928f87b2420b530e22" }
sp-std = { version = "4.0.0-dev", default-features = false, git = "https://github.com/subspace/substrate", rev = "5f0aa1feb7250ac7b8c1b9928f87b2420b530e22" }
subspace-core-primitives = { version = "0.1.0", default-features = false, path = "../subspace-core-primitives" }

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"parity-util-mem/std",
	"serde",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"subspace-core-primitives/std",
]
