[package]
name = "subspace-networking"
version = "0.1.1"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>", "Shamil Gadelshin <shamilgadelshin@gmail.com>"]
description = "Networking functionality of Subspace Network, primarily used for DSN (Distributed Storage Network)"
edition = "2021"
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/subspace/subspace"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
event-listener-primitives = "2.0.1"
bytes = "1.1.0"
futures = "0.3.21"
hex = "0.4.3"
nohash-hasher = "0.2.0"
parking_lot = "0.12.0"
subspace-core-primitives = { version = "0.1.0", path = "../subspace-core-primitives" }
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = ["macros", "parking_lot", "rt-multi-thread", "time"] }
tracing = "0.1"
uint = "0.9.3"
unsigned-varint = { version = "0.7.1", features = ["futures", "asynchronous_codec"] }
async-trait = "0.1"
bincode = "1.3.3"
serde = "1.0.137"

[dependencies.libp2p]
version = "0.44.0"
default-features = false
features = [
    "dns-tokio",
    "gossipsub",
    "identify",
    "kad",
    "noise",
    "ping",
    "tcp-tokio",
    "websocket",
    "yamux",
    "request-response"
]

[dev-dependencies]
anyhow = "1.0.57"
clap = { version = "3.1.18", features = ["color", "derive"] }
env_logger = "0.9.0"
tracing-subscriber = "0.2"
rand = "0.7.2"