[package]
name = "subspace-networking"
version = "0.1.0"
authors = [
    "Nazar Mokrynskyi <nazar@mokrynskyi.com>",
    "Shamil Gadelshin <shamilgadelshin@gmail.com>"
]
description = "Networking functionality of Subspace Network, primarily used for DSN (Distributed Storage Network)"
edition = "2021"
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/subspace/subspace"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
async-mutex = "1.4.0"
actix-web = "4.4.0"
async-trait = "0.1.73"
backoff = { version = "0.4.0", features = ["futures", "tokio"] }
bytes = "1.5.0"
clap = { version = "4.4.3", features = ["color", "derive"] }
derive_more = "0.99.17"
either = "1.8.1"
event-listener-primitives = "2.0.1"
fs2 = "0.4.3"
futures = "0.3.28"
futures-timer = "3.0.2"
hex = "0.4.3"
lru = "0.11.0"
memmap2 = "0.7.1"
nohash-hasher = "0.2.0"
parity-scale-codec = "3.6.5"
parking_lot = "0.12.1"
pin-project = "1.1.3"
prometheus-client = "0.21.2"
rand = "0.8.5"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.106"
subspace-core-primitives = { version = "0.1.0", path = "../subspace-core-primitives" }
subspace-metrics = { version = "0.1.0", path = "../../shared/subspace-metrics" }
thiserror = "1.0.48"
tokio = { version = "1.32.0", features = ["macros", "parking_lot", "rt-multi-thread", "sync", "time"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"]}
unsigned-varint = { version = "0.7.1", features = ["futures", "asynchronous_codec"] }
void = "1.0.2"

[dependencies.libp2p]
git = "https://github.com/shamil-gadelshin/rust-libp2p"
rev = "7a9328fc0a5f9e28575192d5f4f8663fde6752af"
default-features = false
features = [
    "autonat",
    "dns",
    "gossipsub",
    "identify",
    "kad",
    "macros",
    "metrics",
    "noise",
    "ping",
    "plaintext",
    "quic",
    "request-response",
    "serde",
    "tcp",
    "tokio",
    "yamux",
]

[dev-dependencies]
rand = "0.8.5"
libp2p-swarm-test = "0.2.0"
